apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: roboshop
  labels:
    app: nginx
    project: roboshop
spec:
  containers:
    - name: nginx-container
      image: nginx:1.21
      ports:
        - containerPort: 80
