apiVersion: v1
kind: pod
metadata:
  name: frontend
  labels:
    project: roboshop
    course: Devops
    trainer: Satish
    version: v1
spec:
  containers:
  - name: frontend
    image: nginx
    
